user:
  name_maximum: 50
  email_maximum: 255
  pass_minimum: 6
  phone_maximum: 10
  address_maximum: 200
  gravatar_user: 50
user_helper:
  gravatar_length: 80
  male: "Male"
  female: "Female"
publisher:
  name_maximum: 150
  description_maximum: 1500
comment:
  content_maximum: 1500
Category:
  name_maximum: 50
book:
  name_maximum: 150
  pages_maximum: 5000
  amount_maximum: 50000
  number:
    min_length: 1
  length_seemore: 20
  maximun_image: 5
author:
  name_maximum: 50
paginate:
  per_page: 20
